//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantsyHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int IdDoctor { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int Specialization { get; set; }
        public int Department { get; set; }
        public string Login { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Specializations Specializations { get; set; }
        public virtual Users Users { get; set; }
    }
}
